  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: udagram-user-api
        image: forsythetony/udagram_user_api:f20767f0
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: api-secrets
        env:
          - name: UDAGRAM_POSTGRES_HOST
            value: "udagram-user-feed-db.cognlgykyfwj.us-east-2.rds.amazonaws.com"
          - name: UDAGRAM_POSTGRES_USERNAME
            value: "postgres"
          - name: UDAGRAM_POSTGRES_DB
            value: "postgres"