  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: udagram-user-api
        image: forsythetony/udagram_user_api:fae732ca
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: api-secrets
        env:
          - name: UDAGRAM_POSTGRES_HOST
            value: "udagram-user-feed-db.cognlgykyfwj.us-east-2.rds.amazonaws.com"
          - name: UDAGRAM_POSTGRES_USERNAME
            value: "postgres"
          - name: UDAGRAM_POSTGRES_DB
            value: "postgres"
          - name: UDAGRAM_FRONTEND_URL
            value: "http://a73bff37a9b4543679d683955d8f8ccd-dd9ba5b14d51e505.elb.us-east-2.amazonaws.com"
