  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: udagram-user-api
        image: forsythetony/udagram_user_api:f20767f0
        ports:
        - containerPort: 8080
