kind: Deployment
apiVersion: apps/v1
metadata:
  name: udagram
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: forsythetony/udagram_frontend:d6cbbeff
        ports:
        - containerPort: 80