apiVersion: v1
kind: Service

metadata:
  name: reverseproxy-elb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - name: http
      protocol: TCP
      port: 8080